### ISSUE TITLE
Weekly meetings scheduling

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/Cooperative#10]
We should have weekly meetings where everyone gets together in a voice chat or zoom chat. This would provide a platform for board members to inform all members as to what is going on and it would provide a platform for all contributors to weigh in with their opinions.

We should probably hold these meetings with specific agendas so as not to go off on too many tangents.

The meetings should also either be recorded or summarized in documents.

For now, I think we should schedule a specific time every week for these meetings.

6PM EST on Thursdays seems like it could work well.

I need everyone's opinions on the timing of this!

**Comment by james8bc** [comment]
That time works most weeks for me.

**Comment by james8bc** [comment]
I also think it is a great thing to do.

**Comment by activescott** [comment]
Since this is 3PM US-west-coast time I may not always be able to make it, but I will call in when I can (which I expect to be a majority of the time).

I would like to propose the following requirements for each meeting:

1. A formal agenda is prepared in advance. Any community member can suggest an agenda item and any single board member can adopt an agenda item. We probably should have a maximum number of agenda items.
2. A standard end time (30-60 minutes).
3. A designated volunteer recorder of meeting minutes (we can also use a board member rotation in the event of no volunteer). They should record Agenda, Discussions, Decisions, and Action Items during the meeting and post the meeting minutes publicly in a github issue (or file in a repo folder) each meeting.
4. A standard dial-in location (our existing Discord voice channel seems to be fine).

Concerns? Suggestions? Supportive? Please comment or react w/ emoji.

**Comment by Simon0x** [comment]
It is 12AM at my local time, but that should work for me :)

**Comment by JonathonDunford** [comment]
@activescott 

I think we should have recordings along with the recording of meeting minutes.

**Comment by FinanceRebellion** [comment]
6pm est on Thursdays is perfect for me. I work mon-fri, 9-5 est, But am typically home by six. My schedule outside of that is pretty flexible.

**Comment by JonathonDunford** [comment]
Okay, it's official. 6PM ET on Thursday is our official meeting time.

To see what time that is in your timezone, you can use this handy tool: https://www.worldtimebuddy.com/?pl=1&lid=5&h=5

These discussions will include a recap of the week as well as discussions about future plans and QAs. We will need to set official agendas for the meetings in the future.

These meetings will be held using  Zoom and meeting links will be posted in #members in our Discord server.
